server:
  port: 5001
spring:
  application:
    name: stream-rabbitmq
  cloud:
    stream:
      bindings:
        demo_channel:
          group: demoGroup
          destination: demoDest
      rabbit:
        bindings:
          demo_channel:
            consumer:
              exchangeType: direct
              bindingRoutingKey: demoRoutingKey
              autoBindDlq: true
              republishToDlq: true
            producer:
              exchangeType: direct
              bindingRoutingKey: demoRoutingKey
  rabbitmq:
        virtual-host: /
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest