server:
  port: 5001
spring:
  application:
    name: stream-rabbitmq
  cloud:
    stream:
      bindings:
        demo_channel:
          group: demoGroup
        demo2_channel:
          group: demoGroup
      rabbit:
        bindings:
          demo_channel:
            consumer:
              exchangeType: direct
              autoBindDlq: true
              republishToDlq: true
              deadLetterQueueName: dead.letter.queue
              deadLetterRoutingKey: dead.letter.routing.key
              bindingRoutingKey: demoRoutingKey
            producer:
              exchangeType: direct
              bindingRoutingKey: demoRoutingKey
          demo2_channel:
            consumer:
              exchangeType: direct
              autoBindDlq: true
              republishToDlq: true
              deadLetterQueueName: dead.letter.queue
              deadLetterRoutingKey: dead.letter.routing.key
              bindingRoutingKey: demoRoutingKey
            producer:
              exchangeType: direct
              bindingRoutingKey: demoRoutingKey
          dead_letter_channel:
            consumer:
              exchangeType: direct
            producer:
              exchangeType: direct
  rabbitmq:
        virtual-host: /
        host: localhost
        username: guest
        password: guest