server:
  port: 5001
spring:
  application:
    name: stream-rabbitmq
  cloud:
    stream:
      bindings:
        demo_channel:
          group: demoGroup
          destination: demoDest
        dead_letter_channel:
          group: deadLetterGroup
          destination: deadLetterDest
      rabbit:
        bindings:
          demo_channel:
            consumer:
              exchangeType: direct
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: deadLetterDest
              deadLetterQueueName: deadLetterDest.deadLetterGroup
            producer:
              exchangeType: direct
          dead_letter_channel:
            consumer:
              exchangeType: direct
            producer:
              exchangeType: direct
  rabbitmq:
        virtual-host: /
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest